<?php 
       $cliente="";
       $vendedor="";
       $vehiculo="";
       $pago=""
      if(isset($_POST['cliente']))$cliente=$_POST['cliente'];
      if(isset($_POST['vendedor']))$vendedor=$_POST['vendedor'];
      if(isset($_POST['vehiculo']))$vehiculo=$_POST['vehiculo'];
      if(isset($_POST['pago']))$pago=$_POST['pago'];
        ?>